INSERT INTO author(name, created_at, updated_at)
VALUES ('William Shakespeare', now(), now()),
       ('Agatha Christie', now(), now()),
       ('Barbara Cartland', now(), now()),
       ('Danielle Steel', now(), now()),
       ('Harold Robbins', now(), now()),
       ('Georges Simenon', now(), now()),
       ('Enid Blyton', now(), now()),
       ('Sидney Sheldon', now(), now()),
       ('J. K. Rowling', now(), now()),
       ('Gilbert Patten', now(), now()),
       ('Dr. Seuss', now(), now()),
       ('Eiichiro Oda', now(), now()),
       ('Akira Toriyama', now(), now()),
       ('Leo Tolstoy', now(), now()),
       ('Corín Tellado', now(), now()),
       ('Dean Koontz', now(), now()),
       ('Jackie Collins', now(), now()),
       ('Horatio Alger', now(), now()),
       ('Nora Roberts', now(), now()),
       ('R. L. Stine', now(), now()),
       ('Alexander Pushkin', now(), now()),
       ('Stephen King', now(), now()),
       ('Paulo Coelho', now(), now()),
       ('Jirôn Akagawa', now(), now()),
       ('Jeffrey Archer', now(), now()),
       ('Louis L''Amour', now(), now()),
       ('René Goscinny', now(), now()),
       ('Erle Stanley Gardner', now(), now()),
       ('Edgar Wallace', now(), now()),
       ('Janet Dailey', now(), now());

INSERT INTO news (title, content, author_id, created_at, updated_at)
VALUES ('GENERAL PROVISIONS', 'A Nigerian boy solves a 30-year math equation, is recognized by a Japanese university.',
        1, NOW(), NOW()),
       ('EXECUTIVE', 'Monsanto will close three of its facilities. We are making a difference!', 2, NOW(), NOW()),
       ('LEGISLATURE', 'Rosa Parks has been honored with a reserved front seat on Texas buses.', 3, NOW(), NOW()),
       ('JUDICIARY', 'This little boy giving his sister bone marrow, even though he believed it would kill him.', 4,
        NOW(), NOW()),
       ('ADMINISTRATIVE PROCEDURES AND SERVICES',
        'A city letting people pay parking fines with canned goods for the hungry.', 5, NOW(), NOW()),
       ('AERONAUTICS', 'The 18-year old grandson taking his grandma to prom, and other feel-goods.', 6, NOW(), NOW()),
       ('AGRICULTURE AND ANIMALS',
        'The janitor and cook who turned from workers to volunteers of a center after it closed, to take care of the elderly.',
        7, NOW(), NOW()),
       ('AGRICULTURE, CONSERVATION AND FORESTRY', 'Swipe right for peace-a dating app for conflict resolution.', 8,
        NOW(), NOW()),
       ('AMUSEMENTS AND SPORTS', 'The movie, Human proving the beauty of diversity, and inspiring this article.', 9,
        NOW(), NOW()),
       ('BANKS AND FINANCIAL INSTITUTIONS',
        'A man with an intestinal tumor offering unconditional love through Craigslist ads, and sparking a chain of love.',
        10, NOW(), NOW()),
       ('MAINE CONSUMER CREDIT CODE',
        'A psychic daughter confiding in her mum, I have had a lot of mums but you are the best by far.', 11, NOW(),
        NOW()),
       ('FINANCIAL INSTITUTIONS',
        'One patient recounting: "My doctor ordered a $6,000 treatment machine, to accelerate my healing. The cost for me to use this machine for the next month? Zero."',
        12, NOW(), NOW()),
       ('COMMERCE AND TRADE', 'The white woman standing her ground, defending an elderly black man.', 13, NOW(), NOW()),
       ('UNIFORM COMMERCIAL CODE',
        'This morality Christmas ad with the joyful twist, which will make your eyelids sweaty.', 14, NOW(), NOW()),
       ('CONSERVATION', 'A landlords heartwarming Christmas present.', 15, NOW(), NOW()),
       ('CORPORATIONS', 'Nineteen of the very best uplifting photos of the day.', 16, NOW(), NOW()),
       ('MAINE BUSINESS CORPORATION ACT', 'San Franciscos mobile shower truck for the homeless.', 17, NOW(), NOW()),
       ('MAINE NONPROFIT CORPORATION ACT',
        'Ex-Bengal, Devon Still, whose social media posts about his daughters stage-four neuroblastoma cancer went viral, announcing his baby girls remission.',
        18, NOW(), NOW()),
       ('COURT PROCEDURE -- CIVIL', 'This MN refugee center fielding 4-5 times the needed amount of people to help.',
        19, NOW(), NOW()),
       ('COURT PROCEDURE -- CRIMINAL',
        'WWGSA and these moving words from transplanted international students discovering the love for their American host families: "I love it here you are all so nice to me."',
        20, NOW(), NOW()),
       ('COURT PROCEDURE -- EVIDENCE', 'You are the best American Mom & Dad I could ever ask for."', 21, NOW(), NOW()),
       ('CRIMES', 'The church that tipped a pizza guy who is in recovery $700. Warning, the tears will flow.', 22,
        NOW(), NOW()),
       ('MAINE CRIMINAL CODE',
        'The reaction of a dog rescued by a firefighter. in the words, of GMP Lead Editor, Shawn Henfling, "Dogs are my favorite people."',
        23, NOW(), NOW()),
       ('DECEDENTS ESTATES AND FIDUCIARY RELATIONS',
        'A woman with rare, autoimmune disease, transverse myelitis, gets her bathroom redone so it is wheelchair accessible, all services and materials are donated by a local contractor company.',
        24, NOW(), NOW()),
       ('PROBATE CODE', 'The worst flood in India in 100 years brings Twitter to the rescue.', 25, NOW(), NOW()),
       ('TRUSTS', 'Washington High School students afforded discretion as their food and hygiene needs are met.', 26,
        NOW(), NOW()),
       ('PROBATE CODE', 'One mans drastic 400 pound weight loss spurred on by supportive gym pals.', 27, NOW(), NOW()),
       ('DOMESTIC RELATIONS', 'This dedication to eradicating a killer disease.', 28, NOW(), NOW()),
       ('COMPENSATION', 'An inspiring couple recreating their wedding photo 70 years later.', 29, NOW(), NOW()),
       ('Agriculture, Conservation, and Forestry ',
        'A man fulfilling a young girls wish for a new toy from Santa, described in a letter that literally dropped from the sky.',
        30, NOW(),
        NOW()),
       ('Ex-Bengal, Devon Still, whose social media posts about his daughters stage-four neuroblastoma cancer went viral,
        announcing his baby girls remission.',
        'A secret decoration mission that helped this widow rediscover her holiday spirit.', 1, NOW(), NOW());

INSERT INTO tag(name)
VALUES ('News'),
       ('Entertainment'),
       ('Business'),
       ('Health'),
       ('Science'),
       ('Travel'),
       ('Music'),
       ('Pets'),
       ('Books'),
       ('Fashion'),
       ('Gaming'),
       ('Technology'),
       ('Sports'),
       ('Food');

INSERT INTO news_tag(news_id, tag_id)
VALUES (1, 1),
       (2, 2),
       (3, 3),
       (4, 4),
       (5, 5),
       (6, 6),
       (7, 7),
       (8, 8),
       (9, 9),
       (10, 10),
       (11, 11),
       (12, 12),
       (13, 13),
       (14, 14),
       (15, 1),
       (16, 2),
       (17, 3),
       (18, 4),
       (19, 5),
       (20, 6),
       (21, 7),
       (22, 8),
       (23, 9),
       (24, 10),
       (25, 11),
       (26, 12),
       (27, 13),
       (28, 14),
       (29, 1),
       (30, 2);

INSERT INTO comment(content, news_id, created_at, updated_at)
VALUES ('The best news ever!', 1, NOW(), NOW()),
       ('I agree!', 2, NOW(), NOW()),
       ('I disagree!', 3, NOW(), NOW()),
       ('I don''t know!', 4, NOW(), NOW()),
       ('I don''t know!', 5, NOW(), NOW()),
       ('I don''t know!', 6, NOW(), NOW()),
       ('I don''t know!', 7, NOW(), NOW()),
       ('I don''t know!', 8, NOW(), NOW()),
       ('I don''t know!', 9, NOW(), NOW()),
       ('I don''t know!', 10, NOW(), NOW()),
       ('I don''t know!', 11, NOW(), NOW()),
       ('I don''t know!', 12, NOW(), NOW()),
       ('I don''t know!', 13, NOW(), NOW()),
       ('I don''t know!', 14, NOW(), NOW()),
       ('I don''t know!', 15, NOW(), NOW()),
       ('I don''t know!', 16, NOW(), NOW()),
       ('I don''t know!', 17, NOW(), NOW()),
       ('I don''t know!', 18, NOW(), NOW()),
       ('I don''t know!', 19, NOW(), NOW()),
       ('I don''t know!', 20, NOW(), NOW()),
       ('I don''t know!', 21, NOW(), NOW()),
       ('I don''t know!', 22, NOW(), NOW());